# This workflow will build a .NET project
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
 # Sub Folder (.sln file contained here)
    defaults:
      run:
        working-directory: Task4_CalculatorApp
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  # CD (Continuous Deployment) Operation
    - name: Publish the App (Compile for Production)
      run: dotnet publish --configuration Release --output ./publish

    - name: Upload Production Files (CD Practice)
      uses: actions/upload-artifact@v4
      with:
        name: production-build
        path: ${{ github.workspace }}/Task4_CalculatorApp/publish/
